/* eslint-disable no-useless-catch */
/* eslint-disable no-useless-assignment */
import { ProjectData, ProjectFile } from '../components/HamAiStudio/types';
import { NativeGit } from '../plugins/NativeGit';

const GITHUB_API_BASE = 'https://api.github.com';

export interface GitHubUser {
  login: string;
  avatar_url: string;
  html_url: string;
}

export const githubService = {
  async verifyToken(token: string): Promise<GitHubUser> {
    const response = await fetch(`${GITHUB_API_BASE}/user`, {
      headers: {
        Authorization: `token ${token}`,
        Accept: 'application/vnd.github.v3+json',
      },
    });

    if (!response.ok) {
      throw new Error('Invalid GitHub Token');
    }

    return response.json();
  },

  async createRepo(token: string, name: string, description: string): Promise<Record<string, unknown>> {
    const response = await fetch(`${GITHUB_API_BASE}/user/repos`, {
      method: 'POST',
      headers: {
        Authorization: `token ${token}`,
        Accept: 'application/vnd.github.v3+json',
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        name,
        description,
        private: true, // Default to private for safety
        auto_init: true, // Initialize with README to allow immediate commits
      }),
    });

    if (response.status === 422) {
      // Repo might already exist, check user repos
      const user = await this.verifyToken(token);
      return { html_url: `https://github.com/${user.login}/${name}`, name };
    }

    if (!response.ok) {
      throw new Error('Failed to create repository');
    }

    return response.json();
  },

  async setupGitHubPagesDeployment(token: string, repoName: string, user: GitHubUser): Promise<void> {
    // Create a GitHub Actions workflow file for GitHub Pages deployment
    const workflowContent = `name: Deploy to GitHub Pages
on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist
  deploy:
    environment:
      name: github-pages
      url: \${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
`;

    const encodedContent = btoa(workflowContent);

    // Push the workflow file
    await fetch(`${GITHUB_API_BASE}/repos/${user.login}/${repoName}/contents/.github/workflows/deploy.yml`, {
      method: 'PUT',
      headers: {
        Authorization: `token ${token}`,
        Accept: 'application/vnd.github.v3+json',
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        message: 'Add GitHub Pages deployment workflow',
        content: encodedContent,
        branch: 'main'
      }),
    });
  },

  async syncProject(token: string, project: ProjectData, user: GitHubUser): Promise<string> {
    const repoName = project.name.toLowerCase().replace(/\s+/g, '-').replace(/[^a-z0-9-]/g, '');
    let repo: Record<string, unknown>;
    
    try {
      // Try to get the repo first
      const getResponse = await fetch(`${GITHUB_API_BASE}/repos/${user.login}/${repoName}`, {
        headers: { Authorization: `token ${token}` }
      });
      
      if (getResponse.ok) {
        repo = await getResponse.json() as Record<string, unknown>;
      } else {
        repo = await this.createRepo(token, repoName, `Generated by Ham AI Studio: ${project.name}`);
      }
    } catch (e) {
      // Error ensuring repo
      throw e;
    }

    // ANTI-SIMULATION: Integrasi Git Native (JGit)
    try {
      const projectDir = `HamStudio/Projects/${repoName}`;
      const remoteUrl = `https://${token}@github.com/${user.login}/${repoName}.git`;
      
      // Try native commit and push
      const commitResult = await NativeGit.commit({
        path: projectDir,
        message: `Sync from Ham AI Studio: ${new Date().toLocaleString()}`,
        authorName: user.login,
        authorEmail: `${user.login}@users.noreply.github.com`
      });

      if (commitResult.success) {
        const pushResult = await NativeGit.push({
          path: projectDir,
          remote: remoteUrl,
          branch: 'main',
          token: token
        });
        
        if (pushResult.success) {
          // Successfully synced via Native JGit
          return (repo.html_url as string) || `https://github.com/${user.login}/${repoName}`;
        }
      }
    } catch (nativeError) {
      // Native Git (JGit) not available or failed, falling back to GitHub HTTP API
    }

    // Fallback to HTTP API (Existing logic)
    // 2. Get the latest commit SHA to base our new commit on
    let latestCommitSha;
    try {
        const refResponse = await fetch(`${GITHUB_API_BASE}/repos/${user.login}/${repoName}/git/refs/heads/main`, {
            headers: { Authorization: `token ${token}` }
        });
        if (refResponse.ok) {
            const refData = await refResponse.json();
            latestCommitSha = refData.object.sha;
        }
    } catch (e) {
        // Branch might not exist yet if auto_init failed or empty
    }

    // 3. Create Blobs for each file
    const fileTree: Record<string, unknown>[] = [];
    
    for (const file of project.files) {
      const blobResponse = await fetch(`${GITHUB_API_BASE}/repos/${user.login}/${repoName}/git/blobs`, {
        method: 'POST',
        headers: {
          Authorization: `token ${token}`,
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          content: file.content,
          encoding: 'utf-8',
        }),
      });

      if (blobResponse.ok) {
        const blobData = await blobResponse.json();
        fileTree.push({
          path: file.path,
          mode: '100644',
          type: 'blob',
          sha: blobData.sha,
        });
      }
    }

    // 4. Create Tree
    const treePayload: Record<string, unknown> = { tree: fileTree };
    if (latestCommitSha) {
        treePayload.base_tree = latestCommitSha;
    }

    const treeResponse = await fetch(`${GITHUB_API_BASE}/repos/${user.login}/${repoName}/git/trees`, {
      method: 'POST',
      headers: {
        Authorization: `token ${token}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(treePayload),
    });

    if (!treeResponse.ok) throw new Error('Failed to create git tree');
    const treeData = await treeResponse.json();

    // 5. Create Commit
    const commitResponse = await fetch(`${GITHUB_API_BASE}/repos/${user.login}/${repoName}/git/commits`, {
      method: 'POST',
      headers: {
        Authorization: `token ${token}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        message: `Sync from Ham AI Studio: ${new Date().toLocaleString()}`,
        tree: treeData.sha,
        parents: latestCommitSha ? [latestCommitSha] : [],
      }),
    });

    if (!commitResponse.ok) throw new Error('Failed to create commit');
    const commitData = await commitResponse.json();

    // 6. Update Reference (Force Push)
    const updateRefResponse = await fetch(`${GITHUB_API_BASE}/repos/${user.login}/${repoName}/git/refs/heads/main`, {
      method: 'PATCH', // Use PATCH to update existing ref
      headers: {
        Authorization: `token ${token}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        sha: commitData.sha,
        force: true,
      }),
    });

    if (!updateRefResponse.ok && !latestCommitSha) {
         await fetch(`${GITHUB_API_BASE}/repos/${user.login}/${repoName}/git/refs`, {
            method: 'POST',
            headers: {
                Authorization: `token ${token}`,
                'Content-Type': 'application/json',
            },
            body: JSON.stringify({
                ref: 'refs/heads/main',
                sha: commitData.sha,
            }),
        });
    }

    return (repo.html_url as string) || `https://github.com/${user.login}/${repoName}`;
  }
};
