 
export const STRINGS = {
  SIDEBAR: {
    HOME: 'Home',
    PROJECTS: 'Projects',
    SETTINGS: 'Settings',
    AI_HUB: 'AI Hub',
    TERMINAL: 'Terminal',
    FILES: 'Files',
    GIT: 'Git',
    LOGCAT: 'Logcat',
    PREVIEW: 'Preview',
    BUILD: 'Build',
    DEPLOY: 'Deploy',
    HELP: 'Help',
    LOGOUT: 'Logout',
    PROFILE: 'Profile',
    NOTIFICATIONS: 'Notifications',
    SEARCH: 'Search',
    NEW_PROJECT: 'New Project',
    IMPORT_PROJECT: 'Import Project',
    EXPORT_PROJECT: 'Export Project',
    DELETE_PROJECT: 'Delete Project',
    RENAME_PROJECT: 'Rename Project',
    CLONE_REPO: 'Clone Repository',
    PUSH_REPO: 'Push Repository',
    PULL_REPO: 'Pull Repository',
    COMMIT_CHANGES: 'Commit Changes',
    DISCARD_CHANGES: 'Discard Changes',
    STASH_CHANGES: 'Stash Changes',
    MERGE_BRANCH: 'Merge Branch',
    CREATE_BRANCH: 'Create Branch',
    DELETE_BRANCH: 'Delete Branch',
    SWITCH_BRANCH: 'Switch Branch',
    FETCH_REMOTE: 'Fetch Remote',
    ADD_REMOTE: 'Add Remote',
    REMOVE_REMOTE: 'Remove Remote',
    SHOW_LOGS: 'Show Logs',
    CLEAR_LOGS: 'Clear Logs',
    FILTER_LOGS: 'Filter Logs',
    EXPORT_LOGS: 'Export Logs',
    SETTINGS_GENERAL: 'General Settings',
    SETTINGS_EDITOR: 'Editor Settings',
    SETTINGS_THEME: 'Theme Settings',
    SETTINGS_KEYBINDINGS: 'Keybindings',
    SETTINGS_EXTENSIONS: 'Extensions',
    SETTINGS_ACCOUNT: 'Account Settings',
    SETTINGS_ABOUT: 'About',
    SETTINGS_FEEDBACK: 'Feedback',
    SETTINGS_PRIVACY: 'Privacy Policy',
    SETTINGS_TERMS: 'Terms of Service',
    SETTINGS_LICENSE: 'License',
    SETTINGS_VERSION: 'Version',
    SETTINGS_UPDATE: 'Check for Updates',
    SETTINGS_RESET: 'Reset Settings',
    SETTINGS_BACKUP: 'Backup Settings',
    SETTINGS_RESTORE: 'Restore Settings',
    SETTINGS_SYNC: 'Sync Settings',
    SETTINGS_LANGUAGE: 'Language',
    SETTINGS_FONT: 'Font',
    SETTINGS_FONT_SIZE: 'Font Size',
    SETTINGS_LINE_HEIGHT: 'Line Height',
    SETTINGS_TAB_SIZE: 'Tab Size',
    SETTINGS_WORD_WRAP: 'Word Wrap',
    SETTINGS_MINIMAP: 'Minimap',
    SETTINGS_RULER: 'Ruler',
    SETTINGS_BRACKET_PAIR_COLORIZATION: 'Bracket Pair Colorization',
    SETTINGS_AUTO_SAVE: 'Auto Save',
    SETTINGS_AUTO_FORMAT: 'Auto Format',
    SETTINGS_AUTO_COMPLETE: 'Auto Complete',
    SETTINGS_SNIPPETS: 'Snippets',
    SETTINGS_EMMET: 'Emmet',
    SETTINGS_LINTING: 'Linting',
    SETTINGS_PRETTIER: 'Prettier',
    SETTINGS_ESLINT: 'ESLint',
    SETTINGS_TYPESCRIPT: 'TypeScript',
    SETTINGS_PYTHON: 'Python',
    SETTINGS_JAVA: 'Java',
    SETTINGS_KOTLIN: 'Kotlin',
    SETTINGS_C: 'C',
    SETTINGS_CPP: 'C++',
    SETTINGS_CSHARP: 'C#',
    SETTINGS_GO: 'Go',
    SETTINGS_RUST: 'Rust',
    SETTINGS_PHP: 'PHP',
    SETTINGS_RUBY: 'Ruby',
    SETTINGS_SWIFT: 'Swift',
    SETTINGS_DART: 'Dart',
    SETTINGS_FLUTTER: 'Flutter',
    SETTINGS_REACT: 'React',
    SETTINGS_VUE: 'Vue',
    SETTINGS_ANGULAR: 'Angular',
    SETTINGS_SVELTE: 'Svelte',
    SETTINGS_NEXTJS: 'Next.js',
    SETTINGS_NUXTJS: 'Nuxt.js',
    SETTINGS_GATSBY: 'Gatsby',
    SETTINGS_ELECTRON: 'Electron',
    SETTINGS_TAURI: 'Tauri',
    SETTINGS_CAPACITOR: 'Capacitor',
    SETTINGS_CORDOVA: 'Cordova',
    SETTINGS_EXPO: 'Expo',
    SETTINGS_REACT_NATIVE: 'React Native',
    SETTINGS_IONIC: 'Ionic',
    SETTINGS_NATIVE_SCRIPT: 'NativeScript',
    SETTINGS_XAMARIN: 'Xamarin',
    SETTINGS_MAUI: 'MAUI',
    SETTINGS_UNITY: 'Unity',
    SETTINGS_UNREAL: 'Unreal',
    SETTINGS_GODOT: 'Godot',
    SETTINGS_ARDUINO: 'Arduino',
    SETTINGS_RASPBERRY_PI: 'Raspberry Pi',
    SETTINGS_ESP32: 'ESP32',
    SETTINGS_STM32: 'STM32',
    SETTINGS_AVR: 'AVR',
    SETTINGS_PIC: 'PIC',
    SETTINGS_FPGA: 'FPGA',
    SETTINGS_VERILOG: 'Verilog',
    SETTINGS_VHDL: 'VHDL',
    SETTINGS_SYSTEM_VERILOG: 'SystemVerilog',
    SETTINGS_MATLAB: 'MATLAB',
    SETTINGS_R: 'R',
    SETTINGS_JULIA: 'Julia',
    SETTINGS_HASKELL: 'Haskell',
    SETTINGS_LUA: 'Lua',
    SETTINGS_PERL: 'Perl',
    SETTINGS_SHELL: 'Shell',
    SETTINGS_POWERSHELL: 'PowerShell',
    SETTINGS_BATCH: 'Batch',
    SETTINGS_MAKEFILE: 'Makefile',
    SETTINGS_CMAKE: 'CMake',
    SETTINGS_GRADLE: 'Gradle',
    SETTINGS_MAVEN: 'Maven',
    SETTINGS_ANT: 'Ant',
    SETTINGS_DOCKER: 'Docker',
    SETTINGS_KUBERNETES: 'Kubernetes',
    SETTINGS_TERRAFORM: 'Terraform',
    SETTINGS_ANSIBLE: 'Ansible',
    SETTINGS_JENKINS: 'Jenkins',
    SETTINGS_GITHUB_ACTIONS: 'GitHub Actions',
    SETTINGS_GITLAB_CI: 'GitLab CI',
    SETTINGS_CIRCLE_CI: 'CircleCI',
    SETTINGS_TRAVIS_CI: 'Travis CI',
    SETTINGS_AZURE_PIPELINES: 'Azure Pipelines',
    SETTINGS_AWS: 'AWS',
    SETTINGS_AZURE: 'Azure',
    SETTINGS_GCP: 'GCP',
    SETTINGS_FIREBASE: 'Firebase',
    SETTINGS_SUPABASE: 'Supabase',
    SETTINGS_MONGODB: 'MongoDB',
    SETTINGS_POSTGRESQL: 'PostgreSQL',
    SETTINGS_MYSQL: 'MySQL',
    SETTINGS_SQLITE: 'SQLite',
    SETTINGS_REDIS: 'Redis',
    SETTINGS_ELASTICSEARCH: 'Elasticsearch',
    SETTINGS_GRAPHQL: 'GraphQL',
    SETTINGS_REST_API: 'REST API',
    SETTINGS_WEBSOCKET: 'WebSocket',
    SETTINGS_GRPC: 'gRPC',
    SETTINGS_MQTT: 'MQTT',
    SETTINGS_AMQP: 'AMQP',
    SETTINGS_KAFKA: 'Kafka',
    SETTINGS_RABBITMQ: 'RabbitMQ',
    SETTINGS_ZEROMQ: 'ZeroMQ',
    SETTINGS_WEBRTC: 'WebRTC',
    SETTINGS_WEBASSEMBLY: 'WebAssembly',
    SETTINGS_WEBGL: 'WebGL',
    SETTINGS_WEBGPU: 'WebGPU',
    SETTINGS_THREEJS: 'Three.js',
    SETTINGS_BABYLONJS: 'Babylon.js',
    SETTINGS_PHASER: 'Phaser',
    SETTINGS_PIXIJS: 'PixiJS',
    SETTINGS_D3: 'D3.js',
    SETTINGS_CHARTJS: 'Chart.js',
    SETTINGS_RECHARTS: 'Recharts',
    SETTINGS_HIGHCHARTS: 'Highcharts',
    SETTINGS_AG_GRID: 'AG Grid',
    SETTINGS_MATERIAL_UI: 'Material UI',
    SETTINGS_ANT_DESIGN: 'Ant Design',
    SETTINGS_CHAKRA_UI: 'Chakra UI',
    SETTINGS_TAILWIND_CSS: 'Tailwind CSS',
    SETTINGS_BOOTSTRAP: 'Bootstrap',
    SETTINGS_SASS: 'Sass',
    SETTINGS_LESS: 'Less',
    SETTINGS_STYLUS: 'Stylus',
    SETTINGS_POSTCSS: 'PostCSS',
    SETTINGS_WEBPACK: 'Webpack',
    SETTINGS_ROLLUP: 'Rollup',
    SETTINGS_PARCEL: 'Parcel',
    SETTINGS_VITE: 'Vite',
    SETTINGS_ESBUILD: 'esbuild',
    SETTINGS_SWC: 'SWC',
    SETTINGS_BABEL: 'Babel',
    SETTINGS_JEST: 'Jest',
    SETTINGS_MOCHA: 'Mocha',
    SETTINGS_CHAI: 'Chai',
    SETTINGS_JASMINE: 'Jasmine',
    SETTINGS_CYPRESS: 'Cypress',
    SETTINGS_PLAYWRIGHT: 'Playwright',
    SETTINGS_PUPPETEER: 'Puppeteer',
    SETTINGS_SELENIUM: 'Selenium',
    SETTINGS_APPIUM: 'Appium',
    SETTINGS_DETOX: 'Detox',
    SETTINGS_STORYBOOK: 'Storybook',
    SETTINGS_LADLE: 'Ladle',
    SETTINGS_BIT: 'Bit',
    SETTINGS_NX: 'Nx',
    SETTINGS_TURBOREPO: 'Turborepo',
    SETTINGS_LERNA: 'Lerna',
    SETTINGS_YARN: 'Yarn',
    SETTINGS_NPM: 'npm',
    SETTINGS_PNPM: 'pnpm',
    SETTINGS_BUN: 'Bun',
    SETTINGS_DENO: 'Deno',
    SETTINGS_NODEJS: 'Node.js',
  }
};
