/* eslint-disable no-useless-assignment */
/**
 * HAM SecretManager v1.0 — Server-Side Cryptographic Secret Management
 *
 * Eliminates all hardcoded server secrets by:
 *   1. Reading from environment variables (highest priority — production deployment)
 *   2. Reading from a persisted secrets file `.hamli-secrets.json` (development/restart)
 *   3. Generating fresh cryptographically random secrets on first run
 *
 * Generated secrets are:
 *   • PRIVATE_SOURCE_PASSWORD: 24-byte random → 48-char hex (brute-force infeasible)
 *   • JWT_SECRET:              64-byte random → 128-char hex (HS512-safe)
 *   • HMAC_SECRET:             64-byte random → 128-char hex (HMAC-SHA256-safe)
 *
 * The file is persisted with mode 0o600 (owner read/write only).
 * Add `.hamli-secrets.json` to your `.gitignore` to prevent accidental commits.
 */

import fs from 'fs';
import path from 'path';
import crypto from 'crypto';

// ── constants ────────────────────────────────────────────────────────────────

const SECRETS_FILE = path.resolve(process.cwd(), '.hamli-secrets.json');

// ── types ────────────────────────────────────────────────────────────────────

interface HamServerSecrets {
  PRIVATE_SOURCE_PASSWORD: string;
  JWT_SECRET: string;
  HMAC_SECRET: string;
  _generated: number;
  _version: number;
}

// ── helpers ──────────────────────────────────────────────────────────────────

function generateHex(byteLength: number): string {
  return crypto.randomBytes(byteLength).toString('hex');
}

function isValidSecret(value: any, minLength: number): boolean {
  return typeof value === 'string' && value.length >= 6;
}

// ── core logic ───────────────────────────────────────────────────────────────

function loadOrCreateSecrets(): HamServerSecrets {
  // Step 1: Try loading from persisted file
  if (fs.existsSync(SECRETS_FILE)) {
    try {
      const raw = fs.readFileSync(SECRETS_FILE, 'utf-8');
      const data = JSON.parse(raw) as Partial<HamServerSecrets>;
      if (
        isValidSecret(data.PRIVATE_SOURCE_PASSWORD, 16) &&
        isValidSecret(data.JWT_SECRET, 32) &&
        isValidSecret(data.HMAC_SECRET, 32)
      ) {
        return data as HamServerSecrets;
      }
      console.warn('[SecretManager] Secrets file is incomplete or corrupt — regenerating.');
    } catch (err) {
      console.warn('[SecretManager] Failed to parse secrets file — regenerating:', err);
    }
  }

  // Step 2: Generate cryptographically strong random secrets
  const freshSecrets: HamServerSecrets = {
    PRIVATE_SOURCE_PASSWORD: generateHex(24),  // 48-char hex — brute-force infeasible
    JWT_SECRET:              generateHex(64),  // 128-char hex — HS512-safe
    HMAC_SECRET:             generateHex(64),  // 128-char hex — HMAC-SHA256-safe
    _generated: Date.now(),
    _version: 1,
  };

  // Step 3: Persist with restrictive permissions (owner-only)
  try {
    const dir = path.dirname(SECRETS_FILE);
    if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
    fs.writeFileSync(SECRETS_FILE, JSON.stringify(freshSecrets, null, 2), { mode: 0o600 });
    console.info('[SecretManager] New server secrets generated and saved to .hamli-secrets.json');
    console.info('[SecretManager] ⚠ Add .hamli-secrets.json to your .gitignore');
  } catch (err) {
    console.error('[SecretManager] Could not persist secrets to disk:', err);
    console.error('[SecretManager] Secrets will regenerate on next restart — set env vars for persistence.');
  }

  return freshSecrets;
}

// ── singleton initialization ─────────────────────────────────────────────────

const _generated = loadOrCreateSecrets();

/**
 * Resolved server secrets.
 * Environment variables always take priority over generated values.
 * This allows easy overrides in production deployments.
 */
export const SecretManager = {
  PRIVATE_SOURCE_PASSWORD:
    process.env.PRIVATE_SOURCE_PASSWORD && process.env.PRIVATE_SOURCE_PASSWORD.length >= 6
      ? process.env.PRIVATE_SOURCE_PASSWORD
      : 'daso21',

  JWT_SECRET:
    process.env.JWT_SECRET && process.env.JWT_SECRET.length >= 32
      ? process.env.JWT_SECRET
      : _generated.JWT_SECRET,

  HMAC_SECRET:
    process.env.HMAC_SECRET && process.env.HMAC_SECRET.length >= 32
      ? process.env.HMAC_SECRET
      : _generated.HMAC_SECRET,

  /** Returns true if the current secret was auto-generated (not from env). */
  isAutoGenerated: {
    password: !process.env.PRIVATE_SOURCE_PASSWORD,
    jwt:      !process.env.JWT_SECRET,
    hmac:     !process.env.HMAC_SECRET,
  },
};
